/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  canvasFolder: "",
  nodeWidth: 400,
  nodeHeight: 600
};
var MyPluginSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Dossier Canvas").setDesc("S\xE9lectionnez le dossier o\xF9 enregistrer les canvas").addText((text) => text.setPlaceholder("Exemple: Dossier/Sous-dossier").setValue(this.plugin.settings.canvasFolder).onChange(async (value) => {
      this.plugin.settings.canvasFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Largeur des n\u0153uds").setDesc("Sp\xE9cifiez la largeur des n\u0153uds dans le canvas (en pixels)").addText((text) => text.setPlaceholder("400").setValue(String(this.plugin.settings.nodeWidth)).onChange(async (value) => {
      const numValue = Number(value);
      if (!isNaN(numValue) && numValue > 0) {
        this.plugin.settings.nodeWidth = numValue;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Hauteur des n\u0153uds").setDesc("Sp\xE9cifiez la hauteur des n\u0153uds dans le canvas (en pixels)").addText((text) => text.setPlaceholder("600").setValue(String(this.plugin.settings.nodeHeight)).onChange(async (value) => {
      const numValue = Number(value);
      if (!isNaN(numValue) && numValue > 0) {
        this.plugin.settings.nodeHeight = numValue;
        await this.plugin.saveSettings();
      }
    }));
  }
};
var MyPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.stack = [];
    this.preservedNotes = [];
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MyPluginSettingTab(this.app, this));
    this.addCommand({
      id: "ajouter-note",
      name: "Ajouter Note",
      callback: () => this.addNote()
    });
    this.addCommand({
      id: "ignorer-note",
      name: "Ignorer Note",
      callback: () => this.ignoreNote()
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async addNote() {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile) {
      await this.preserveNote(activeFile);
    }
  }
  async ignoreNote() {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile) {
      await this.discardNote(activeFile);
    }
  }
  async preserveNote(file) {
    if (!this.preservedNotes.includes(file)) {
      this.preservedNotes.push(file);
      const linkedFiles = await this.getLinksAndBacklinks(file);
      for (const linkedFile of linkedFiles) {
        if (!this.stack.includes(linkedFile) && !this.preservedNotes.includes(linkedFile)) {
          this.stack.push(linkedFile);
        }
      }
    }
    new import_obsidian.Notice(`Il reste ${this.stack.length} notes \xE0 traiter.`);
    this.processNextNote();
  }
  async discardNote(file) {
    this.processNextNote();
  }
  async getLinksAndBacklinks(file) {
    var _a;
    const linkedFiles = [];
    const links = ((_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.links) || [];
    const backlinks = this.app.metadataCache.getBacklinksForFile(file);
    for (const link of links) {
      const linkedFilePath = this.app.metadataCache.getFirstLinkpathDest(link.link, file.path);
      if (linkedFilePath) {
        const linkedFile = this.app.vault.getAbstractFileByPath(linkedFilePath.path);
        if (linkedFile instanceof import_obsidian.TFile) {
          linkedFiles.push(linkedFile);
        }
      }
    }
    for (const backlink of Object.keys(backlinks.data)) {
      const backlinkFile = this.app.vault.getAbstractFileByPath(backlink);
      if (backlinkFile instanceof import_obsidian.TFile) {
        linkedFiles.push(backlinkFile);
      }
    }
    return linkedFiles;
  }
  async processNextNote() {
    if (this.stack.length > 0) {
      const nextFile = this.stack.shift();
      if (nextFile) {
        await this.app.workspace.getLeaf().openFile(nextFile);
      }
    } else {
      const fileName = await this.getFileNameFromModal();
      if (fileName) {
        await this.createAndDisplayCanvas(fileName, this.app.workspace.getLeaf());
      }
      this.resetPlugin();
    }
  }
  async getFileNameFromModal() {
    return new Promise((resolve) => {
      new FileNameModal(this.app, resolve).open();
    });
  }
  async createAndDisplayCanvas(fileName, leaf) {
    const canvasContent = this.generateCanvasContent();
    const fullFileName = `${fileName}.canvas`;
    let filePath = fullFileName;
    if (this.settings.canvasFolder) {
      filePath = `${this.settings.canvasFolder}/${fullFileName}`;
      const folderExists = await this.app.vault.adapter.exists(this.settings.canvasFolder);
      if (!folderExists) {
        try {
          await this.app.vault.adapter.mkdir(this.settings.canvasFolder);
        } catch (error) {
          new import_obsidian.Notice(`Erreur lors de la cr\xE9ation du dossier : ${error.message}`);
          return;
        }
      }
    }
    try {
      const canvasFile = await this.app.vault.create(filePath, canvasContent);
      await leaf.openFile(canvasFile);
    } catch (error) {
      new import_obsidian.Notice(`Erreur lors de la cr\xE9ation du canvas : ${error.message}`);
    }
  }
  generateCanvasContent() {
    const nodes = [];
    const edges = [];
    const noteCount = this.preservedNotes.length;
    const columns = Math.ceil(Math.sqrt(noteCount));
    const nodeWidth = this.settings.nodeWidth;
    const nodeHeight = this.settings.nodeHeight;
    const spacingX = 40;
    const spacingY = 40;
    this.preservedNotes.forEach((file, index) => {
      const x = index % columns * (nodeWidth + spacingX);
      const y = Math.floor(index / columns) * (nodeHeight + spacingY);
      nodes.push(`
        {
            "id": "node-${index}",
            "x": ${x},
            "y": ${y},
            "width": ${nodeWidth},
            "height": ${nodeHeight},
            "type": "file",
            "file": "${file.path}"
        }`);
    });
    return `{
    "nodes":[${nodes.join(",")}],
    "edges":[${edges.join(",")}]
}`;
  }
  resetPlugin() {
    this.stack = [];
    this.preservedNotes = [];
  }
};
var FileNameModal = class extends import_obsidian.Modal {
  constructor(app, resolve) {
    super(app);
    this.resolve = resolve;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Enter the file name" });
    this.input = new import_obsidian.TextComponent(contentEl);
    this.input.inputEl.style.width = "100%";
    this.input.inputEl.focus();
    this.input.inputEl.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        event.preventDefault();
        event.stopPropagation();
        this.submitFileName();
      }
    });
    const buttonContainer = contentEl.createDiv();
    buttonContainer.style.display = "flex";
    buttonContainer.style.justifyContent = "flex-end";
    buttonContainer.style.marginTop = "10px";
    new import_obsidian.ButtonComponent(buttonContainer).setButtonText("Cancel").onClick(() => {
      this.close();
      this.resolve(null);
    });
    new import_obsidian.ButtonComponent(buttonContainer).setButtonText("Submit").setCta().onClick(() => {
      this.submitFileName();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  submitFileName() {
    const fileName = this.input.getValue();
    if (fileName) {
      this.close();
      this.resolve(fileName);
    } else {
      new import_obsidian.Notice("Please enter a file name");
    }
  }
};
