/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => InlineEncrypterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/ModalPassword.ts
var import_obsidian = require("obsidian");
var ModalPassword = class extends import_obsidian.Modal {
  constructor(app) {
    super(app);
    this.password = "";
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h1", { text: "Enter password" });
    new import_obsidian.Setting(contentEl).setName("Password").addText((text) => {
      text.inputEl.type = "password";
      text.inputEl.addEventListener("keypress", (event) => {
        if (event.key === "Enter") {
          this.passwordOk();
        }
      });
      text.onChange((value) => this.password = value);
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("OK").setCta().onClick(() => {
      this.passwordOk();
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  passwordOk() {
    this.isPassword = true;
    this.close();
  }
};

// src/CryptoFactory.ts
var CryptoFactory = class {
  constructor() {
    this.vectorSize = 16;
    this.saltSize = 16;
    this.iterations = 262144;
  }
  convertArrayToString(bytes) {
    let result = "";
    for (let i = 0; i < bytes.length; i++) {
      result += String.fromCharCode(bytes[i]);
    }
    return result;
  }
  convertStringToArray(str) {
    const result = [];
    for (let i = 0; i < str.length; i++) {
      result.push(str.charCodeAt(i));
    }
    return new Uint8Array(result);
  }
  async deriveKey(password, salt) {
    const utf8Encoder = new TextEncoder();
    const keyData = utf8Encoder.encode(password);
    const key = await crypto.subtle.importKey("raw", keyData, { name: "PBKDF2" }, false, ["deriveKey"]);
    const privateKey = await crypto.subtle.deriveKey(
      {
        name: "PBKDF2",
        hash: { name: "SHA-512" },
        salt,
        iterations: this.iterations
      },
      key,
      {
        name: "AES-GCM",
        length: 256
      },
      false,
      ["encrypt", "decrypt"]
    );
    return privateKey;
  }
  async encryptToBytes(text, password) {
    const salt = crypto.getRandomValues(new Uint8Array(this.saltSize));
    const key = await this.deriveKey(password, salt);
    const utf8Encoder = new TextEncoder();
    const textBytesToEncrypt = utf8Encoder.encode(text);
    const vector = crypto.getRandomValues(new Uint8Array(this.vectorSize));
    const encryptedBytes = new Uint8Array(
      await crypto.subtle.encrypt(
        {
          name: "AES-GCM",
          iv: vector
        },
        key,
        textBytesToEncrypt
      )
    );
    const finalBytes = new Uint8Array(vector.byteLength + salt.byteLength + encryptedBytes.byteLength);
    finalBytes.set(vector, 0);
    finalBytes.set(salt, vector.byteLength);
    finalBytes.set(encryptedBytes, vector.byteLength + salt.byteLength);
    return finalBytes;
  }
  async encryptToBase64(text, password) {
    const finalBytes = await this.encryptToBytes(text, password);
    const base64Text = btoa(this.convertArrayToString(finalBytes));
    return base64Text;
  }
  async decryptFromBytes(encryptedBytes, password) {
    try {
      let offset;
      let nextOffset;
      offset = 0;
      nextOffset = offset + this.vectorSize;
      const vector = encryptedBytes.slice(offset, nextOffset);
      offset = nextOffset;
      nextOffset = offset + this.saltSize;
      const salt = encryptedBytes.slice(offset, nextOffset);
      offset = nextOffset;
      nextOffset = void 0;
      const encryptedTextBytes = encryptedBytes.slice(offset);
      const key = await this.deriveKey(password, salt);
      const decryptedBytes = await crypto.subtle.decrypt(
        {
          name: "AES-GCM",
          iv: vector
        },
        key,
        encryptedTextBytes
      );
      const utf8Decoder = new TextDecoder();
      const decryptedText = utf8Decoder.decode(decryptedBytes);
      return decryptedText;
    } catch (e) {
      return null;
    }
  }
  async decryptFromBase64(base64Encoded, password) {
    try {
      const bytesToDecode = this.convertStringToArray(atob(base64Encoded));
      return await this.decryptFromBytes(bytesToDecode, password);
    } catch (e) {
      return null;
    }
  }
};

// src/UiHelper.ts
var import_obsidian3 = require("obsidian");

// src/ModalDecrypt.ts
var import_obsidian2 = require("obsidian");
var ModalDecrypt = class extends import_obsidian2.Modal {
  constructor(app, text = "") {
    super(app);
    this.text = text;
  }
  onOpen() {
    var _a;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.classList.add("inline-encrypter-decrypt-modal");
    contentEl.createEl("h1", { text: "Decrypted secret" });
    let textArea;
    const textVal = new import_obsidian2.Setting(contentEl).addTextArea((cb) => {
      textArea = cb;
      cb.setValue(this.text);
      cb.inputEl.setSelectionRange(0, 0);
      cb.inputEl.readOnly = true;
      cb.inputEl.rows = 10;
    });
    (_a = textVal.settingEl.querySelector(".setting-item-info")) == null ? void 0 : _a.remove();
    const buttons = new import_obsidian2.Setting(contentEl);
    buttons.addButton((cb) => {
      cb.setButtonText("Copy to clipboard").onClick((evt) => {
        navigator.clipboard.writeText(textArea.getValue());
        new import_obsidian2.Notice("Secret copied");
      });
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/Constants.ts
var ENCRYPTED_CODE_PREFIX = "secret";

// src/UiHelper.ts
var UiHelper = class {
  handleDecryptClick(app, event, input) {
    event.preventDefault();
    const cryptoFactory = new CryptoFactory();
    const passModal = new ModalPassword(app);
    passModal.onClose = async () => {
      if (!passModal.isPassword) {
        return;
      }
      input = input.replace(ENCRYPTED_CODE_PREFIX, "").replace(/`/g, "").replace(/\s/g, "").replace(/\r?\n|\r/g, "");
      const output = await cryptoFactory.decryptFromBase64(input, passModal.password);
      if (output === null) {
        new import_obsidian3.Notice("\u274C Decryption failed!");
        return;
      } else {
        new ModalDecrypt(app, output).open();
      }
    };
    passModal.open();
  }
  selectionAndRangeOverlap(selection, rangeFrom, rangeTo) {
    for (const range of selection.ranges) {
      if (range.from <= rangeTo && range.to >= rangeFrom) {
        return true;
      }
    }
    return false;
  }
};

// src/LivePreviewExtension.ts
var import_obsidian4 = require("obsidian");
var import_view2 = require("@codemirror/view");
var import_state = require("@codemirror/state");
var import_language = require("@codemirror/language");

// src/InlineWidget.ts
var import_view = require("@codemirror/view");
var InlineWidget = class extends import_view.WidgetType {
  constructor(app, value) {
    super();
    this.app = app;
    this.value = value;
  }
  toDOM(view) {
    const uiHelper = new UiHelper();
    const div = document.createElement("div");
    div.addClass("inline-encrypter-lp-code");
    const a = div.createEl("a");
    a.addClass("inline-encrypter-code");
    a.onClickEvent((event) => uiHelper.handleDecryptClick(this.app, event, this.value));
    return div;
  }
};

// src/LivePreviewExtension.ts
var livePreviewExtension = (app) => import_view2.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.decorations = this.buildDecorations(view);
    }
    update(update) {
      if (!update.state.field(import_obsidian4.editorLivePreviewField)) {
        this.decorations = import_view2.Decoration.none;
        return;
      }
      if (update.docChanged || update.viewportChanged || update.selectionSet) {
        this.decorations = this.buildDecorations(update.view);
      }
    }
    destroy() {
    }
    buildDecorations(view) {
      if (!view.state.field(import_obsidian4.editorLivePreviewField))
        return import_view2.Decoration.none;
      const uiHelper = new UiHelper();
      const builder = new import_state.RangeSetBuilder();
      const selection = view.state.selection;
      for (const { from, to } of view.visibleRanges) {
        (0, import_language.syntaxTree)(view.state).iterate({
          from,
          to,
          enter(node) {
            if (node.type.name.startsWith("inline-code")) {
              const value = view.state.doc.sliceString(node.from, node.to);
              const isEncrypted = value.indexOf(ENCRYPTED_CODE_PREFIX) === 0;
              if (isEncrypted) {
                if (!uiHelper.selectionAndRangeOverlap(selection, node.from - 1, node.to + 1)) {
                  builder.add(
                    node.from,
                    node.to,
                    import_view2.Decoration.replace({
                      widget: new InlineWidget(app, value)
                    })
                  );
                }
              }
            }
          }
        });
      }
      return builder.finish();
    }
  },
  {
    decorations: (instance) => instance.decorations
  }
);

// src/main.ts
var InlineEncrypterPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.cryptoFactory = new CryptoFactory();
  }
  async onload() {
    this.registerMarkdownPostProcessor((el, ctx) => this.processEncryptedInlineCodeBlockProcessor(el, ctx));
    this.registerMarkdownCodeBlockProcessor(ENCRYPTED_CODE_PREFIX, (source, el, ctx) => this.processEncryptedCodeBlockProcessor(source, el, ctx));
    this.registerEditorExtension(livePreviewExtension(this.app));
    this.addCommand({
      id: "encrypt",
      name: "Encrypt selected text",
      icon: "lock",
      editorCallback: (editor, view) => this.processInlineEncryptCommand(editor, 0 /* Inline */)
    });
    this.addCommand({
      id: "encrypt-code",
      name: "Encrypt selected text as code block",
      icon: "lock",
      editorCallback: (editor, view) => this.processInlineEncryptCommand(editor, 1 /* Common */)
    });
    this.addCommand({
      id: "decrypt",
      name: "Decrypt selected text",
      icon: "lock",
      editorCallback: (editor, view) => this.processInlineDecryptCommand(editor)
    });
    console.log("Inline Encrypter plugin loaded");
  }
  onunload() {
    console.log("Inline Encrypter plugin unloaded");
  }
  async processInlineEncryptCommand(editor, codeBlockType) {
    if (editor.somethingSelected()) {
      const input = editor.getSelection();
      const passModal = new ModalPassword(this.app);
      passModal.onClose = async () => {
        if (!passModal.isPassword) {
          return;
        }
        const output = await this.cryptoFactory.encryptToBase64(input, passModal.password);
        if (codeBlockType === 0 /* Inline */) {
          editor.replaceSelection("`" + ENCRYPTED_CODE_PREFIX + " " + output + "`");
        }
        if (codeBlockType === 1 /* Common */) {
          editor.replaceSelection("```" + ENCRYPTED_CODE_PREFIX + "\n" + output + "\n```");
        }
        if (passModal.password.length === 0) {
          new import_obsidian5.Notice("\u26A0\uFE0F Password is empty");
        }
        new import_obsidian5.Notice("\u2705 Text encrypted");
      };
      passModal.open();
    } else {
      new import_obsidian5.Notice("\u274C No selected text for encryption");
    }
  }
  async processInlineDecryptCommand(editor) {
    if (editor.somethingSelected()) {
      let input = editor.getSelection();
      const passModal = new ModalPassword(this.app);
      passModal.onClose = async () => {
        if (!passModal.isPassword) {
          return;
        }
        input = input.replace(ENCRYPTED_CODE_PREFIX, "").replace(/`/g, "").replace(/\s/g, "").replace(/\r?\n|\r/g, "");
        const output = await this.cryptoFactory.decryptFromBase64(input, passModal.password);
        if (output === null) {
          new import_obsidian5.Notice("\u274C Decryption failed!");
          return;
        } else {
          editor.replaceSelection(output);
          new import_obsidian5.Notice("\u2705 Text decrypted");
        }
      };
      passModal.open();
    } else {
      new import_obsidian5.Notice("\u274C No selected text for decryption");
    }
  }
  processEncryptedInlineCodeBlockProcessor(el, ctx) {
    const codeblocks = el.querySelectorAll("code");
    for (let i = 0; i < codeblocks.length; i++) {
      const codeblock = codeblocks.item(i);
      const text = codeblock.innerText.trim();
      const isEncrypted = text.indexOf(ENCRYPTED_CODE_PREFIX) === 0;
      if (isEncrypted) {
        const uiHelper = new UiHelper();
        codeblock.innerText = "";
        codeblock.createEl("a", { cls: "inline-encrypter-code" });
        codeblock.onClickEvent((event) => uiHelper.handleDecryptClick(this.app, event, text));
      }
    }
  }
  processEncryptedCodeBlockProcessor(source, el, ctx) {
    const uiHelper = new UiHelper();
    const codeblock = el.createEl("a", { cls: "inline-encrypter-code" });
    codeblock.onClickEvent((event) => uiHelper.handleDecryptClick(this.app, event, source));
  }
};
